### ISSUE TITLE
Ambiguous error messages

### ISSUE THREAD

**Issue by kumarharsh** [css-modules/postcss-icss-composes#129]
This module throws some very hard-to-decipher error messages, such as:

> composition is only allowed when selector is single :local class name not in ":local(.input):local(.thin-size)"
or
> composition is only allowed when selector is single :local class name not in XXX, YYY is weird

I think there are some commas missing, which make all of this very hard to understand. I mean, I get the 'general' idea, but what am I (as a developer) supposed to do about it? and what does the "... is weird" mean?

Also, https://github.com/css-modules/postcss-modules-scope/blob/42708f1298fa0e7515d5006d7c00d1f07cef9e9e/src/index.js#L23 says in the comment that "// 'id' is not possible, because you can't compose ids". I think that's a better error message for that case than the current one.

**Comment by joshwnj** [comment]
@kumarharsh good call. Would you like to try an attempt at rewriting the error message here on the issue, to make it clearer?  Then we can PR.

We basically need to get the idea across in this message that you can only use `composes` on classes, and it must be a single class selector.

**Comment by kumarharsh** [comment]
Yes, sure.

**Comment by kumarharsh** [comment]
@joshwnj I've tried to clarify the wording, see if it helps. I thought of making the errors more granular, but too many checks weren't making a lot of sense either...
