### ISSUE TITLE
option for unique and un-readable class name 

### ISSUE THREAD

**Issue by morlay** [css-modules/postcss-icss-composes#14]
Scoped css, a wonderful idea.

Someone have the same way to make scoped css work (https://github.com/maxguzenski/react-easy-style), but not good to generate class names when running. 
Now css modules fix this, we can make the class names as static strings before running.

Could we add an option to make the unique string **shorter** and **un-readable** ? 
maybe used in production

**Comment by geelen** [comment]
Yep, [css-loader](https://github.com/webpack/css-loader) has a `localIdentName` property where you can make the generated class what you want. I think it's possible in [css-modulesify](https://github.com/css-modules/css-modulesify) as well, and it'll be available in the JSPM loader soon too.

**Comment by morlay** [comment]
Finally, found it.
It need to set option `generateScopedName` to plugin `postcss-modules-scope`

``` js
function createScopedNameFunc(plugin) {
  var orig = plugin.generateScopedName;
  return function (name, path, css) {
    var hash = stringHash(css).toString(36).substr(0, 5);
    return orig.apply(plugin, arguments) + '___' + hash;
  }
};
```

Haven't find any document about this. :crying_cat_face:
