### ISSUE TITLE
Consider split keyframes handling

### ISSUE THREAD

**Issue by TrySound** [css-modules/postcss-icss-composes#159]
1. Will be better for performance to process only two properties (`animation`, `animation-frame`) instead of all.
2. Splitting in separate module will let to remove some stuff from `local-by-default` and this plugins and just use new module without ugly `_colon_local` stuff.

/cc @sullenor @geelen

**Comment by mightyaleksey** [comment]
I don't mind about it, just little worried about that we would have to implement scope thing for the animation names.

**Comment by TrySound** [comment]
Keyframes scope is a bit different then classnames. It processes also properties with ugly midifier.

For now scope is two plugins with a lot of code. We need to split them to increase supportness.

Also local mode makes importing keyframes from  another file problematic.
