### ISSUE TITLE
Don't set Container#nodes directly

### ISSUE THREAD

**Issue by ai** [css-modules/postcss-icss-composes#71]
You should set children by `append()` or any other inset methods (of course, except `push()`).

Here we have same problem as with `push()`: PostCSS will not fix issues for you as result it is easy to broke AST.

In result we have issue in other PostCSS plugins like this: https://github.com/ben-eb/cssnano/issues/163#issuecomment-208214467

**Comment by ai** [comment]
@geelen if you don’t have a time to fix it (I know it, I have bug open source project too), just say that you need help and users will send a PR.

Ignoring a issue for 3 weeks is very rude :'(

**Comment by ai** [comment]
@geelen we even have a PR https://github.com/css-modules/postcss-modules-scope/pull/77

You just need to accept it and release new version. If you have not time (I understand it too), I can find a guy who will help you with project maintaining.

**Comment by madyankin** [comment]
@geelen +1. I think this is a really important fix and it should be merged.

**Comment by ben-eb** [comment]
Can we get this fixed? 👍
